# Generated by Django 4.1 on 2023-01-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Published_date", models.DateTimeField(auto_created=True)),
                ("Image", models.ImageField(upload_to="")),
                ("Title", models.CharField(max_length=1000)),
                ("Content", models.TextField()),
            ],
        ),
    ]
