# Generated by Django 4.1 on 2023-01-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0002_alter_article_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="Image",
            new_name="poster",
        ),
    ]
