# Generated by Django 4.1 on 2023-01-10 06:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0003_rename_image_article_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="Slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="Title", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="Published_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
