# Generated by Django 4.1 on 2023-01-10 15:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0004_article_slug_alter_article_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="Published_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="poster",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
