# Generated by Django 4.1.5 on 2023-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0010_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                (
                    "Post",
                    models.ManyToManyField(
                        related_name="subjects", to="idiosaneapp.article"
                    ),
                ),
            ],
        ),
    ]
