# Generated by Django 4.1.5 on 2023-01-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0011_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="Post",
        ),
        migrations.AddField(
            model_name="article",
            name="Category",
            field=models.ManyToManyField(
                default=None, related_name="category", to="idiosaneapp.subject"
            ),
        ),
    ]
