# Generated by Django 4.1.5 on 2023-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0012_remove_subject_post_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="Name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
