# Generated by Django 4.1.5 on 2023-01-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idiosaneapp", "0013_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="Category",
            field=models.ManyToManyField(
                default=None, related_name="posts", to="idiosaneapp.subject"
            ),
        ),
    ]
